"""empty message

Revision ID: 330b980694fb
Revises: cbabda0d8ad8
Create Date: 2016-05-18 09:32:49.558047

"""

# revision identifiers, used by Alembic.
revision = '330b980694fb'
down_revision = 'cbabda0d8ad8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('givelight_user', sa.Column('city', sa.String(length=64), nullable=False))
    op.add_column('givelight_user', sa.Column('country', sa.String(length=64), nullable=False))
    op.add_column('givelight_user', sa.Column('state', sa.String(length=64), nullable=False))
    op.alter_column('givelight_user', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('givelight_user', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('givelight_user', 'password',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.alter_column('givelight_user', 'role',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('givelight_user', 'role',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('givelight_user', 'password',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.alter_column('givelight_user', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('givelight_user', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('givelight_user', 'state')
    op.drop_column('givelight_user', 'country')
    op.drop_column('givelight_user', 'city')
    ### end Alembic commands ###
