"""empty message

Revision ID: 60db277fe45d
Revises: 7ebbed47c591
Create Date: 2016-05-18 23:27:24.455413

"""

# revision identifiers, used by Alembic.
revision = '60db277fe45d'
down_revision = '7ebbed47c591'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('givelight_skill',
    sa.Column('id', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('user_id', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['givelight_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('givelight_skill')
    ### end Alembic commands ###
