"""empty message

Revision ID: 96b3ed92512a
Revises: c962813e4754
Create Date: 2016-05-18 23:56:59.033602

"""

# revision identifiers, used by Alembic.
revision = '96b3ed92512a'
down_revision = 'c962813e4754'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'givelight_department_event_id_fkey', 'givelight_department', type_='foreignkey')
    op.drop_column('givelight_department', 'event_id')
    op.add_column('givelight_user', sa.Column('department_name', sa.String(length=1024), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('givelight_user', 'department_name')
    op.add_column('givelight_department', sa.Column('event_id', sa.VARCHAR(length=1024), autoincrement=False, nullable=False))
    op.create_foreign_key(u'givelight_department_event_id_fkey', 'givelight_department', 'givelight_event', ['event_id'], ['id'])
    ### end Alembic commands ###
